from typing import Optional

class TasksDB:
    def create(self, title: str, content: str) -> tuple[int, str, str]: ...

    def read_all(self) -> list[tuple[int, str, str]]: ...

    def read_one(self, id: int) -> tuple[int, str, str]: ...

    def update(self, t: tuple[int, str, str]) -> Optional[tuple[int, str, str]]: ...

    def delete(self, id: int) -> int: ...
